# Generated by Django 6.0.2 on 2026-02-25 16:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_block'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['rated_user'], name='idx_rating_rated_user'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.UniqueConstraint(fields=('rater', 'activity'), name='unique_rating_per_activity_per_rater'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('rater', models.F('rated_user')), _negated=True), name='prevent_self_rating'),
        ),
        migrations.AddConstraint(
            model_name='rating',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 1), ('score__lte', 5)), name='score_range_1_to_5'),
        ),
    ]
